# Lucida Engine — funding links
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [BlackLineInteractive]

custom:
  - https://t.me/blacklineinteractive
